---
inputs:
  secret_gh_personal_access_token:
    description: "..."
    required: true
  centos8_ami_id:
    description: "..."
    required: true
  subnet_id:
    description: "..."
    required: true
  sg_id:
    description: "..."
    required: true
runs:
  using: "composite"
  steps:
    - name: Start EC2 CentOS Wazuh runner
      id: start-centos-wazuh-ec2-runner
      uses: machulav/ec2-github-runner@v2
      with:
        mode: start
        github-token: ${{ inputs.gh_personal_access_token }}
        ec2-image-id: ${{ inputs.centos8_ami_id }}
        ec2-instance-type: t3.small
        subnet-id: ${{ inputs.subnet_id }}
        security-group-id: ${{ inputs.sg_id }}
        aws-resource-tags: > # optional, requires additional permissions
          [
            {"Key": "Name", "Value": "wazuh-ansible-gh-runner-wazuh"},
            {"Key": "GitHubRepository", "Value": "${{ github.repository }}"},
            {"Key": "team", "Value": "CICD"},
            {"Key": "termination_Date", "Value": "N/A"}
          ]
    - name: Start EC2 CentOS AIO runner
      id: start-centos-aio-ec2-runner
      uses: machulav/ec2-github-runner@v2
      with:
        mode: start
        github-token: ${{ inputs.gh_personal_access_token }}
        ec2-image-id: ${{ inputs.centos8_ami_id }}
        ec2-instance-type: t3a.large
        subnet-id: ${{ inputs.subnet_id }}
        security-group-id: ${{ inputs.sg_id }}
        aws-resource-tags: > # optional, requires additional permissions
          [
            {"Key": "Name", "Value": "wazuh-ansible-gh-runner-aio"},
            {"Key": "GitHubRepository", "Value": "${{ github.repository }}"},
            {"Key": "team", "Value": "CICD"},
            {"Key": "termination_Date", "Value": "N/A"}
          ]