---
name: Wazuh-Single-Instance
on: [push, pull_request, workflow_dispatch, release]
jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label-centos-wazuh: ${{ steps.start-centos-wazuh-ec2-runner.outputs.label }}
      ec2-centos-wazuh-instance-id: ${{ steps.start-centos-wazuh-ec2-runner.outputs.ec2-instance-id }}
      label-centos-aio: ${{ steps.start-centos-aio-ec2-runner.outputs.label }}
      ec2-centos-aio-instance-id: ${{ steps.start-centos-aio-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Create EC2 runners
        uses: ./.github/create_ec2_runners
  install-wazuh-single-instance:
    name: Installs Wazuh server single instance
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.label-centos-wazuh }} # run the job on the newly created runner
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Hack to get setup-python to work on act. See act issue 251
        run: |
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Ansible Playbook run Wazuh Single instance
        run: ansible-playbook ./.github/playbooks/single-wazuh.yml
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
  install-aio-single-instance:
    name: Installs AIO single instance
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.label-centos-aio }} # run the job on the newly created runner
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Hack to get setup-python to work on act. See act issue 251
        run: |
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Ansible Playbook run Wazuh AIO Single instance
        run: ansible-playbook ./.github/playbooks/aio-wazuh.yml
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # required to get output from the start-runner job
      - install-wazuh-single-instance # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 CentOS Wazuh runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label-centos-wazuh }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-centos-wazuh-instance-id }}
      - name: Stop EC2 CentOS AIO runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label-centos-wazuh }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-centos-wazuh-instance-id }}